### PR TITLE
increase flexibility of callback

### PR DESCRIPTION
**Pull request by debanjan-basu**
I added this feature for passing arguments to the callbacks for prints etc. Could not compile the tests due to unavailability of the library.

### CODE REVIEW

**Comment by mellowcandle** [comment]
Hi Shane.
Thanks for the pull request.
I'm not sure I understand.
Why do we need this extra parameter if we pass NULL to it ?
Thanks.
Ramon

**Comment by debanjan-basu** [comment]
If you allow the merge then we can modify functions eg llist_for_each(list, func_ptr, arg) to pass extra arguments along with the node.

**Comment by mellowcandle** [comment]
I searched the net for any reference to list_for_each where there's an
extra argument. I didn't find.
Here's an example for another implementation:
http://www-ad.fnal.gov/help/ul_clib/list_for_each.html

I can't think of any use for this argument.

**Comment by debanjan-basu** [comment]
Think about these two situation for real applications
1. In the list_for_each the callback can require an argument if we are working in a mutithreaded environment, then we need to pass the mutex as an arguemt to the function list_for_each, since the callback will use this mutex to lock for changing anything inside the node.
2. Also very simple cases are like where people need to pass their logger instance to log the node data as they iterate over the list.

Also what I feel is that all callbacks should give the option of passing an argument which the user chooses. (eg pthread_create of POSIX)

**Comment by mellowcandle** [comment]
OK. This sounds reasonable.
I think that introducing a new function: list_for_each_arg is better, as it's doesn't force the developer and doesn't change the current API.

**Comment by debanjan-basu** [comment]
Ok thats fair ..I will get get it done and provide you with a pull req

**Pull request closed without merging**
